apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: demo-app

spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - name: nginx 
      containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-service

spec:
  ports:
  - name: demo-service
    port: 80
    targetPort: 80

  selector:
    app: demo-app

  type: NodePort
